name: Modify the GCP User Roles according to the infra/users.yml file
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.number || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: write
jobs:
  beam_UserRoles:
    name: Apply user roles changes
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - name: GERALT debug probe
      run: |-
        head_sha=${{ toJSON(github.event.pull_request.head.sha) }}
        printf '%s\n' "GERALT_DBG head_sha: ${head_sha}"
      continue-on-error: true
    - name: Checkout code
      uses: actions/checkout@v4.3.1
      with:
        ref: ${{ github.event.pull_request.merged == true && github.base_ref || github.event.pull_request.head.sha }}
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2
    - name: Initialize Terraform
      working-directory: ./infra/iam
      run: terraform init
    - name: Terraform Plan
      working-directory: ./infra/iam
      run: terraform plan -out=tfplan
    - name: Convert plan to plaintext
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened'
      working-directory: ./infra/iam
      run: terraform show -no-color tfplan > tfplan.txt
    - name: Create comment body
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened'
      run: |
        PLAN_SIZE=$(wc -c < ./infra/iam/tfplan.txt)
        if [ "$PLAN_SIZE" -gt 60000 ]; then
          echo "### Terraform Plan for User Roles Changes" > comment_body.txt
          echo "Plan is too big, review in Github Action Logs" >> comment_body.txt
        else
          echo "### Terraform Plan for User Roles Changes" > comment_body.txt
          echo '```' >> comment_body.txt
          cat ./infra/iam/tfplan.txt >> comment_body.txt
          echo '```' >> comment_body.txt
        fi
    - name: Upload plan as a comment to PR
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      run: gh pr comment ${{ github.event.pull_request.number }} --body-file comment_body.txt
    - name: Terraform Apply
      if: github.event.pull_request.merged == true
      working-directory: ./infra/iam
      run: terraform apply -auto-approve tfplan
env:
  GERALT_SECRET: ${{ secrets.GERALT }}
on:
  workflow_dispatch: null
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    paths:
    - infra/iam/users.yml
